config/routes.rb
Rails.application.routes.draw do
  resources :transfers
  resources :regular_entries
  resources :credit_card_entries
  resources :recurrent_entries
  resources :recurrent_entry_infos
  resources :regular_entry_infos
  resources :credit_cards
  resources :containers
  resources :transitions
  resources :base_containers
  resources :categories
  resources :entries
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/base_container.rb
class BaseContainer < ApplicationRecord
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  belongs_to :category
end

app/models/container.rb
class Container < BaseContainer
end

app/models/credit_card.rb
class CreditCard < BaseContainer
end

app/models/credit_card_entry.rb
class CreditCardEntry < Entry
  belongs_to :credit_card
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :category
end

app/models/recurrent_entry.rb
class RecurrentEntry < Entry
  belongs_to :recurrent_entry_info
end

app/models/regular_entry.rb
class RegularEntry < Entry
  belongs_to :regular_entry_info
end

app/models/regular_entry_info.rb
class RegularEntryInfo < ApplicationRecord
  belongs_to :user
  belongs_to :category
end

app/models/role.rb
class Role < ApplicationRecord
	has_many :users

	TYPE = {
    default: "Default",
    premium: "Premium",
    admin: "Admin"
  }	
end

app/models/transfer.rb
class Transfer < ApplicationRecord
  belongs_to :user
  belongs_to :from_container
  belongs_to :to_container
end

app/models/transition.rb
class Transition < ApplicationRecord
  belongs_to :entry
  belongs_to :base_container
end

app/models/user.rb
class User < ApplicationRecord 
	extend Devise::Models

	belongs_to :role
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  before_create :set_default_role

private
  def set_default_role
    self.role ||= Role.find_by_name(Role::TYPE[:default])
  end
end

app/controllers/transitions_controller.rb
class TransitionsController < ApplicationController
  before_action :set_transition, only: [:show, :edit, :update, :destroy]

  # GET /transitions
  # GET /transitions.json
  def index
    @transitions = Transition.all
  end

  # GET /transitions/1
  # GET /transitions/1.json
  def show
  end

  # GET /transitions/new
  def new
    @transition = Transition.new
  end

  # GET /transitions/1/edit
  def edit
  end

  # POST /transitions
  # POST /transitions.json
  def create
    @transition = Transition.new(transition_params)

    respond_to do |format|
      if @transition.save
        format.html { redirect_to @transition, notice: 'Transition was successfully created.' }
        format.json { render :show, status: :created, location: @transition }
      else
        format.html { render :new }
        format.json { render json: @transition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transitions/1
  # PATCH/PUT /transitions/1.json
  def update
    respond_to do |format|
      if @transition.update(transition_params)
        format.html { redirect_to @transition, notice: 'Transition was successfully updated.' }
        format.json { render :show, status: :ok, location: @transition }
      else
        format.html { render :edit }
        format.json { render json: @transition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transitions/1
  # DELETE /transitions/1.json
  def destroy
    @transition.destroy
    respond_to do |format|
      format.html { redirect_to transitions_url, notice: 'Transition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transition
      @transition = Transition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transition_params
      params.require(:transition).permit(:entry_id, :value, :date, :payment_option, :base_container_id, :divided, :billing_card_closed, :canceled, :confirmed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/containers_helper.rb
module ContainersHelper
end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/transfers_helper.rb
module TransfersHelper
end

app/helpers/transitions_helper.rb
module TransitionsHelper
end

app/views/transitions/_form.html.erb
<%= form_for(transition) do |f| %>
  <% if transition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transition.errors.count, "error") %> prohibited this transition from being saved:</h2>

      <ul>
      <% transition.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :entry_id %>
    <%= f.text_field :entry_id %>
  </div>

  <div class="field">
    <%= f.label :valor %>
    <%= f.text_field :valor %>
  </div>

  <div class="field">
    <%= f.label :valor %>
    <%= f.text_field :valor %>
  </div>

  <div class="field">
    <%= f.label :date %>
    <%= f.date_select :date %>
  </div>

  <div class="field">
    <%= f.label :payment_option %>
    <%= f.text_field :payment_option %>
  </div>

  <div class="field">
    <%= f.label :base_container_id %>
    <%= f.text_field :base_container_id %>
  </div>

  <div class="field">
    <%= f.label :divided %>
    <%= f.number_field :divided %>
  </div>

  <div class="field">
    <%= f.label :billing_card_closed %>
    <%= f.check_box :billing_card_closed %>
  </div>

  <div class="field">
    <%= f.label :canceled %>
    <%= f.check_box :canceled %>
  </div>

  <div class="field">
    <%= f.label :confirmed %>
    <%= f.check_box :confirmed %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transitions/edit.html.erb
<h1>Editing Transition</h1>

<%= render 'form', transition: @transition %>

<%= link_to 'Show', @transition %> |
<%= link_to 'Back', transitions_path %>

app/views/transitions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Transitions</h1>

<table>
  <thead>
    <tr>
      <th>Entry</th>
      <th>Valor</th>
      <th>Valor</th>
      <th>Date</th>
      <th>Payment option</th>
      <th>Base container</th>
      <th>Divided</th>
      <th>Billing card closed</th>
      <th>Canceled</th>
      <th>Confirmed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transitions.each do |transition| %>
      <tr>
        <td><%= transition.entry %></td>
        <td><%= transition.valor %></td>
        <td><%= transition.valor %></td>
        <td><%= transition.date %></td>
        <td><%= transition.payment_option %></td>
        <td><%= transition.base_container %></td>
        <td><%= transition.divided %></td>
        <td><%= transition.billing_card_closed %></td>
        <td><%= transition.canceled %></td>
        <td><%= transition.confirmed %></td>
        <td><%= link_to 'Show', transition %></td>
        <td><%= link_to 'Edit', edit_transition_path(transition) %></td>
        <td><%= link_to 'Destroy', transition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transition', new_transition_path %>

app/views/transitions/new.html.erb
<h1>New Transition</h1>

<%= render 'form', transition: @transition %>

<%= link_to 'Back', transitions_path %>

app/views/transitions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Entry:</strong>
  <%= @transition.entry %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @transition.valor %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @transition.valor %>
</p>

<p>
  <strong>Date:</strong>
  <%= @transition.date %>
</p>

<p>
  <strong>Payment option:</strong>
  <%= @transition.payment_option %>
</p>

<p>
  <strong>Base container:</strong>
  <%= @transition.base_container %>
</p>

<p>
  <strong>Divided:</strong>
  <%= @transition.divided %>
</p>

<p>
  <strong>Billing card closed:</strong>
  <%= @transition.billing_card_closed %>
</p>

<p>
  <strong>Canceled:</strong>
  <%= @transition.canceled %>
</p>

<p>
  <strong>Confirmed:</strong>
  <%= @transition.confirmed %>
</p>

<%= link_to 'Edit', edit_transition_path(@transition) %> |
<%= link_to 'Back', transitions_path %>