config/routes.rb
Rails.application.routes.draw do
  resources :transfers
  resources :regular_entries
  resources :credit_card_entries
  resources :recurrent_entries
  resources :recurrent_entry_infos
  resources :regular_entry_infos
  resources :credit_cards
  resources :containers
  resources :transitions
  resources :base_containers
  resources :categories
  resources :entries
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/base_container.rb
class BaseContainer < ApplicationRecord
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  belongs_to :category
end

app/models/container.rb
class Container < BaseContainer
end

app/models/credit_card.rb
class CreditCard < BaseContainer
end

app/models/credit_card_entry.rb
class CreditCardEntry < Entry
  belongs_to :credit_card
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :category
end

app/models/recurrent_entry.rb
class RecurrentEntry < Entry
  belongs_to :recurrent_entry_info
end

app/models/regular_entry.rb
class RegularEntry < Entry
  belongs_to :regular_entry_info
end

app/models/regular_entry_info.rb
class RegularEntryInfo < ApplicationRecord
  belongs_to :user
  belongs_to :category
end

app/models/role.rb
class Role < ApplicationRecord
	has_many :users

	TYPE = {
    default: "Default",
    premium: "Premium",
    admin: "Admin"
  }	
end

app/models/transfer.rb
class Transfer < ApplicationRecord
  belongs_to :user
  belongs_to :from_container
  belongs_to :to_container
end

app/models/transition.rb
class Transition < ApplicationRecord
  belongs_to :entry
  belongs_to :base_container
end

app/models/user.rb
class User < ApplicationRecord 
	extend Devise::Models

	belongs_to :role
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  before_create :set_default_role

private
  def set_default_role
    self.role ||= Role.find_by_name(Role::TYPE[:default])
  end
end

app/controllers/base_containers_controller.rb
class BaseContainersController < ApplicationController
  before_action :set_base_container, only: [:show, :edit, :update, :destroy]

  # GET /base_containers
  # GET /base_containers.json
  def index
    @base_containers = BaseContainer.all
  end

  # GET /base_containers/1
  # GET /base_containers/1.json
  def show
  end

  # GET /base_containers/new
  def new
    @base_container = BaseContainer.new
  end

  # GET /base_containers/1/edit
  def edit
  end

  # POST /base_containers
  # POST /base_containers.json
  def create
    @base_container = BaseContainer.new(base_container_params)

    respond_to do |format|
      if @base_container.save
        format.html { redirect_to @base_container, notice: 'Base container was successfully created.' }
        format.json { render :show, status: :created, location: @base_container }
      else
        format.html { render :new }
        format.json { render json: @base_container.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /base_containers/1
  # PATCH/PUT /base_containers/1.json
  def update
    respond_to do |format|
      if @base_container.update(base_container_params)
        format.html { redirect_to @base_container, notice: 'Base container was successfully updated.' }
        format.json { render :show, status: :ok, location: @base_container }
      else
        format.html { render :edit }
        format.json { render json: @base_container.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /base_containers/1
  # DELETE /base_containers/1.json
  def destroy
    @base_container.destroy
    respond_to do |format|
      format.html { redirect_to base_containers_url, notice: 'Base container was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_base_container
      @base_container = BaseContainer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def base_container_params
      params.require(:base_container).permit(:user_id, :type, :name, :pay_debit, :active)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/base_containers_helper.rb
module BaseContainersHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/containers_helper.rb
module ContainersHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/transfers_helper.rb
module TransfersHelper
end

app/helpers/transitions_helper.rb
module TransitionsHelper
end

app/views/base_containers/_form.html.erb
<%= form_for(base_container) do |f| %>
  <% if base_container.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(base_container.errors.count, "error") %> prohibited this base_container from being saved:</h2>

      <ul>
      <% base_container.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :type %>
    <%= f.text_field :type %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :pay_debit %>
    <%= f.check_box :pay_debit %>
  </div>

  <div class="field">
    <%= f.label :active %>
    <%= f.check_box :active %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/base_containers/edit.html.erb
<h1>Editing Base Container</h1>

<%= render 'form', base_container: @base_container %>

<%= link_to 'Show', @base_container %> |
<%= link_to 'Back', base_containers_path %>

app/views/base_containers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Base Containers</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Type</th>
      <th>Name</th>
      <th>Pay debit</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @base_containers.each do |base_container| %>
      <tr>
        <td><%= base_container.user %></td>
        <td><%= base_container.type %></td>
        <td><%= base_container.name %></td>
        <td><%= base_container.pay_debit %></td>
        <td><%= base_container.active %></td>
        <td><%= link_to 'Show', base_container %></td>
        <td><%= link_to 'Edit', edit_base_container_path(base_container) %></td>
        <td><%= link_to 'Destroy', base_container, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Base Container', new_base_container_path %>

app/views/base_containers/new.html.erb
<h1>New Base Container</h1>

<%= render 'form', base_container: @base_container %>

<%= link_to 'Back', base_containers_path %>

app/views/base_containers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @base_container.user %>
</p>

<p>
  <strong>Type:</strong>
  <%= @base_container.type %>
</p>

<p>
  <strong>Name:</strong>
  <%= @base_container.name %>
</p>

<p>
  <strong>Pay debit:</strong>
  <%= @base_container.pay_debit %>
</p>

<p>
  <strong>Active:</strong>
  <%= @base_container.active %>
</p>

<%= link_to 'Edit', edit_base_container_path(@base_container) %> |
<%= link_to 'Back', base_containers_path %>