config/routes.rb
Rails.application.routes.draw do
  resources :transfers
  resources :regular_entries
  resources :credit_card_entries
  resources :recurrent_entries
  resources :recurrent_entry_infos
  resources :regular_entry_infos
  resources :credit_cards
  resources :containers
  resources :transitions
  resources :base_containers
  resources :categories
  resources :entries
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/base_container.rb
class BaseContainer < ApplicationRecord
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  belongs_to :category
end

app/models/container.rb
class Container < BaseContainer
end

app/models/credit_card.rb
class CreditCard < BaseContainer
end

app/models/credit_card_entry.rb
class CreditCardEntry < Entry
  belongs_to :credit_card
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :category
end

app/models/recurrent_entry.rb
class RecurrentEntry < Entry
  belongs_to :recurrent_entry_info
end

app/models/recurrent_entry_info.rb
class RecurrentEntryInfo < ApplicationRecord
  belongs_to :user
  belongs_to :category
  belongs_to :container
end

app/models/regular_entry.rb
class RegularEntry < Entry
  belongs_to :regular_entry_info
end

app/models/regular_entry_info.rb
class RegularEntryInfo < ApplicationRecord
  belongs_to :user
  belongs_to :category
end

app/models/role.rb
class Role < ApplicationRecord
	has_many :users

	TYPE = {
    default: "Default",
    premium: "Premium",
    admin: "Admin"
  }	
end

app/models/transfer.rb
class Transfer < ApplicationRecord
  belongs_to :user
  belongs_to :from_container
  belongs_to :to_container
end

app/models/transition.rb
class Transition < ApplicationRecord
  belongs_to :entry
  belongs_to :base_container
end

app/models/user.rb
class User < ApplicationRecord 
	extend Devise::Models

	belongs_to :role
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  before_create :set_default_role

private
  def set_default_role
    self.role ||= Role.find_by_name(Role::TYPE[:default])
  end
end

app/controllers/recurrent_entry_infos_controller.rb
class RecurrentEntryInfosController < ApplicationController
  before_action :set_recurrent_entry_info, only: [:show, :edit, :update, :destroy]

  # GET /recurrent_entry_infos
  # GET /recurrent_entry_infos.json
  def index
    @recurrent_entry_infos = RecurrentEntryInfo.all
  end

  # GET /recurrent_entry_infos/1
  # GET /recurrent_entry_infos/1.json
  def show
  end

  # GET /recurrent_entry_infos/new
  def new
    @recurrent_entry_info = RecurrentEntryInfo.new
  end

  # GET /recurrent_entry_infos/1/edit
  def edit
  end

  # POST /recurrent_entry_infos
  # POST /recurrent_entry_infos.json
  def create
    @recurrent_entry_info = RecurrentEntryInfo.new(recurrent_entry_info_params)

    respond_to do |format|
      if @recurrent_entry_info.save
        format.html { redirect_to @recurrent_entry_info, notice: 'Recurrent entry info was successfully created.' }
        format.json { render :show, status: :created, location: @recurrent_entry_info }
      else
        format.html { render :new }
        format.json { render json: @recurrent_entry_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recurrent_entry_infos/1
  # PATCH/PUT /recurrent_entry_infos/1.json
  def update
    respond_to do |format|
      if @recurrent_entry_info.update(recurrent_entry_info_params)
        format.html { redirect_to @recurrent_entry_info, notice: 'Recurrent entry info was successfully updated.' }
        format.json { render :show, status: :ok, location: @recurrent_entry_info }
      else
        format.html { render :edit }
        format.json { render json: @recurrent_entry_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recurrent_entry_infos/1
  # DELETE /recurrent_entry_infos/1.json
  def destroy
    @recurrent_entry_info.destroy
    respond_to do |format|
      format.html { redirect_to recurrent_entry_infos_url, notice: 'Recurrent entry info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recurrent_entry_info
      @recurrent_entry_info = RecurrentEntryInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recurrent_entry_info_params
      params.require(:recurrent_entry_info).permit(:user_id, :category_id, :nature, :name, :estimated_value, :expiration_day, :expiration_date, :quotas, :active, :auto_confirm, :container_id, :auto_adjust)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/containers_helper.rb
module ContainersHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/recurrent_entry_infos_helper.rb
module RecurrentEntryInfosHelper
end

app/helpers/transfers_helper.rb
module TransfersHelper
end

app/views/recurrent_entry_infos/_form.html.erb
<%= form_for(recurrent_entry_info) do |f| %>
  <% if recurrent_entry_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recurrent_entry_info.errors.count, "error") %> prohibited this recurrent_entry_info from being saved:</h2>

      <ul>
      <% recurrent_entry_info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :category_id %>
    <%= f.text_field :category_id %>
  </div>

  <div class="field">
    <%= f.label :nature %>
    <%= f.text_field :nature %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :estimated_value %>
    <%= f.text_field :estimated_value %>
  </div>

  <div class="field">
    <%= f.label :expiration_day %>
    <%= f.number_field :expiration_day %>
  </div>

  <div class="field">
    <%= f.label :expiration_date %>
    <%= f.date_select :expiration_date %>
  </div>

  <div class="field">
    <%= f.label :quotas %>
    <%= f.number_field :quotas %>
  </div>

  <div class="field">
    <%= f.label :active %>
    <%= f.check_box :active %>
  </div>

  <div class="field">
    <%= f.label :auto_confirm %>
    <%= f.check_box :auto_confirm %>
  </div>

  <div class="field">
    <%= f.label :container_id %>
    <%= f.text_field :container_id %>
  </div>

  <div class="field">
    <%= f.label :auto_adjust %>
    <%= f.check_box :auto_adjust %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recurrent_entry_infos/edit.html.erb
<h1>Editing Recurrent Entry Info</h1>

<%= render 'form', recurrent_entry_info: @recurrent_entry_info %>

<%= link_to 'Show', @recurrent_entry_info %> |
<%= link_to 'Back', recurrent_entry_infos_path %>

app/views/recurrent_entry_infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recurrent Entry Infos</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Category</th>
      <th>Nature</th>
      <th>Name</th>
      <th>Estimated value</th>
      <th>Expiration day</th>
      <th>Expiration date</th>
      <th>Quotas</th>
      <th>Active</th>
      <th>Auto confirm</th>
      <th>Container</th>
      <th>Auto adjust</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recurrent_entry_infos.each do |recurrent_entry_info| %>
      <tr>
        <td><%= recurrent_entry_info.user %></td>
        <td><%= recurrent_entry_info.category %></td>
        <td><%= recurrent_entry_info.nature %></td>
        <td><%= recurrent_entry_info.name %></td>
        <td><%= recurrent_entry_info.estimated_value %></td>
        <td><%= recurrent_entry_info.expiration_day %></td>
        <td><%= recurrent_entry_info.expiration_date %></td>
        <td><%= recurrent_entry_info.quotas %></td>
        <td><%= recurrent_entry_info.active %></td>
        <td><%= recurrent_entry_info.auto_confirm %></td>
        <td><%= recurrent_entry_info.container %></td>
        <td><%= recurrent_entry_info.auto_adjust %></td>
        <td><%= link_to 'Show', recurrent_entry_info %></td>
        <td><%= link_to 'Edit', edit_recurrent_entry_info_path(recurrent_entry_info) %></td>
        <td><%= link_to 'Destroy', recurrent_entry_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recurrent Entry Info', new_recurrent_entry_info_path %>

app/views/recurrent_entry_infos/new.html.erb
<h1>New Recurrent Entry Info</h1>

<%= render 'form', recurrent_entry_info: @recurrent_entry_info %>

<%= link_to 'Back', recurrent_entry_infos_path %>

app/views/recurrent_entry_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @recurrent_entry_info.user %>
</p>

<p>
  <strong>Category:</strong>
  <%= @recurrent_entry_info.category %>
</p>

<p>
  <strong>Nature:</strong>
  <%= @recurrent_entry_info.nature %>
</p>

<p>
  <strong>Name:</strong>
  <%= @recurrent_entry_info.name %>
</p>

<p>
  <strong>Estimated value:</strong>
  <%= @recurrent_entry_info.estimated_value %>
</p>

<p>
  <strong>Expiration day:</strong>
  <%= @recurrent_entry_info.expiration_day %>
</p>

<p>
  <strong>Expiration date:</strong>
  <%= @recurrent_entry_info.expiration_date %>
</p>

<p>
  <strong>Quotas:</strong>
  <%= @recurrent_entry_info.quotas %>
</p>

<p>
  <strong>Active:</strong>
  <%= @recurrent_entry_info.active %>
</p>

<p>
  <strong>Auto confirm:</strong>
  <%= @recurrent_entry_info.auto_confirm %>
</p>

<p>
  <strong>Container:</strong>
  <%= @recurrent_entry_info.container %>
</p>

<p>
  <strong>Auto adjust:</strong>
  <%= @recurrent_entry_info.auto_adjust %>
</p>

<%= link_to 'Edit', edit_recurrent_entry_info_path(@recurrent_entry_info) %> |
<%= link_to 'Back', recurrent_entry_infos_path %>